In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
import os
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "/content/drive/MyDrive/spotifyclassifier-b2d573dee4ec.json"
from google.cloud import bigquery
# Construct a BigQuery client ob
client = bigquery.Client()

In [7]:
query_string = """
SELECT * from
spotifyclassifier.features.features_updated
"""

dataframe = (
    client.query(query_string)
    .result()
    .to_dataframe(
    )
)

Get pitch values for each song, split them into separate columns

In [9]:
import pandas as pd 
list_pitches = []
for i in range(len(dataframe)):
    pitches = []
    for j in dataframe['avg_pitches'][i]['list']:
        pitches.append(j['item'])
    list_pitches.append(pitches)
split_df = pd.DataFrame(list_pitches, columns=["pitch" + str(i) for i in range(12)])
split_df

         pitch0    pitch1    pitch2  ...    pitch9   pitch10   pitch11
0      0.166429  0.130373  0.280209  ...  0.123414  0.105160  0.123485
1      0.279721  0.212368  0.374908  ...  0.282957  0.411426  0.225928
2      0.323854  0.253197  0.235020  ...  0.361604  0.275023  0.281492
3      0.298196  0.338050  0.207071  ...  0.227802  0.312116  0.227256
4      0.548001  0.413204  0.195386  ...  0.229627  0.292882  0.305598
...         ...       ...       ...  ...       ...       ...       ...
33109  0.566377  0.640027  0.692849  ...  0.431418  0.288393  0.305517
33110  0.655814  0.693139  0.519790  ...  0.499244  0.352426  0.273599
33111  0.315026  0.345199  0.276372  ...  0.761932  0.328645  0.206549
33112  0.559399  0.743593  0.353880  ...  0.390429  0.356983  0.326345
33113  0.593922  0.390916  0.269748  ...  0.439499  0.609666  0.328445

[33114 rows x 12 columns]

In [ ]:
dataframe = pd.concat([dataframe, split_df], axis=1)
dataframe = dataframe.drop('avg_pitches', axis=1)

Get timbre values for each song, split them into separate columns

In [12]:
list_timbre = []
for i in range(len(dataframe)):
    timbre = []
    for j in dataframe['avg_timbre'][i]['list']:
        timbre.append(j['item'])
    list_timbre.append(timbre)
split_df = pd.DataFrame(list_timbre, columns=["timbre" + str(i) for i in range(12)])
split_df

         timbre0    timbre1    timbre2  ...   timbre9   timbre10   timbre11
0      37.004007 -90.234091  76.550343  ... -7.116997  -9.644667  -8.502539
1      39.728789 -46.906011   3.882081  ... -6.422826 -10.928428  13.846691
2      40.572993 -51.000179   8.265204  ... -1.402933  -5.109533   8.181321
3      36.129289  56.935988 -16.474612  ...  0.386632 -17.826369  -5.611879
4      40.551189  14.553666  22.092379  ...  1.341475  -6.676309  14.716670
...          ...        ...        ...  ...       ...        ...        ...
33109  53.737970  88.661980  23.983986  ...  4.057271  -6.412553   0.494314
33110  54.245286  82.167680  10.401692  ...  8.067857  -7.436330  -2.760537
33111  52.606308  41.804700  18.442318  ...  1.800901  -9.741995   3.086852
33112  52.016924  63.030750   6.572731  ...  7.431930  -7.375142   2.246927
33113  53.758864  59.578352  21.908984  ...  1.652546  -9.228341  -3.397299

[33114 rows x 12 columns]

In [13]:
dataframe = pd.concat([dataframe, split_df], axis=1)
dataframe = dataframe.drop('avg_timbre', axis=1)
dataframe

                           id super_genre  ...   timbre10   timbre11
0      4VMVCovOM1xnOKxzr9Sje5        jazz  ...  -9.644667  -8.502539
1      41CHb7F7SXcmkj0h8wekeF        jazz  ... -10.928428  13.846691
2      0goLt4LXK1MpzwIfmItIS1        jazz  ...  -5.109533   8.181321
3      7ij7UtqIKu2dP1qq5738rV        jazz  ... -17.826369  -5.611879
4      7wyznHrs1tQaeLMRdteaEh        jazz  ...  -6.676309  14.716670
...                       ...         ...  ...        ...        ...
33109  7dbjRLY969SvR0inx3h1eP        rock  ...  -6.412553   0.494314
33110  7gQ7DfSSc3b8e4cHtFnDxu        rock  ...  -7.436330  -2.760537
33111  7kJkTFmKYHrp9LT8w0oqpG        rock  ...  -9.741995   3.086852
33112  7lMFAK8dv0QkWpIlZcWQlJ        rock  ...  -7.375142   2.246927
33113  7z21IYXNRcxdmubc6YG13B        rock  ...  -9.228341  -3.397299

[33114 rows x 53 columns]

Delete rows with more than 5 empty column values

In [ ]:
dataframe = dataframe.loc[dataframe.eq(0).sum(1).le(5),]
dataframe

Drop songs with multiple supergenre labels

In [ ]:
grouped_df = dataframe.groupby("id")
grouped_df = grouped_df.agg({"super_genre": "nunique"})
grouped_df = grouped_df.reset_index()
grouped_df = grouped_df[grouped_df['super_genre'] == 1]  
keep = grouped_df['id'].tolist()
dataframe = dataframe[dataframe['id'].isin(keep)]

Drop songs with multiple subgenre labels

In [ ]:
grouped_df = dataframe.groupby("id")
grouped_df = grouped_df.agg({"subgenre": "nunique"})
grouped_df = grouped_df.reset_index()
grouped_df = grouped_df[grouped_df['subgenre'] == 1]  
keep = grouped_df['id'].tolist()
dataframe = dataframe[dataframe['id'].isin(keep)]

Load dataframe into BigQuery table

In [ ]:
from google.cloud import bigquery
# Construct a BigQuery client object.
client = bigquery.Client()
table_id = "spotifyclassifier.features.features_updated_pit_tim_cols"

In [ ]:
job = client.load_table_from_dataframe(
    dataframe, table_id
)  # Make an API request.
job.result()  # Wait for the job to complete.

In [ ]:
table = client.get_table(table_id)  # Make an API request.
print(
    "Loaded {} rows and {} columns to {}".format(
        table.num_rows, len(table.schema), table_id
    )
)